name: CreateEnvironmentAbstract

authors:
  - Asiya Shaji
  - Humera Sultana

type: ABSTRACT

endpoint: /envs

method: POST

auth: Default

headers:
 - 'Content-Type: application/json'

testCases:
    - id: 1
      body: '{"auths":[{"authType": "Basic","name": "Default",
      "password": "humera123$","username": "Humera//humera@fxlabs.io"}],
      "name": "UAT","baseUrl": "http://13.56.210.25/api/v1",
      "projectId": "{{@create_project_GitHub_abstract_Response.data.id}}"}'

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data.authType == @Request.authType"
  - "@Response.data.username == @Request.username"
  - "@Response.data.name == @Request.name"
  - "@Response.data.url == @Request.url"
  - "@Response.data.project.id == @Request.project.id"

severity: Major

category: Functional

tags:
- V2
