name: DeleteEnvironment

authors:
  - Asiya Shaji
  - Humera Sultana

type: ABSTRACT

endpoint: /envs/{{@Response.data.id}}

method: DELETE

auth: Default

headers:
- 'Content-Type: application/json'

assertions:
    - "@StatusCode == 200"
    - "@Response.errors == false"

severity: Major

category: Functional

tags:
- V2
