name: EnvironmentFindByRating

authors:
  - Asiya Shaji
  - Humera Sultana

type: SUITE

init:
   - CreateEnvironmentAbstract

endpoint: /envs/{{@CreateEnvironmentAbstract_Response.data.id}}/envrating

method: GET

auth: Default

assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data != EMPTY"

cleanup:
    - DeleteEnvironmentAbstract

severity: Major

category: Functional

tags:
    - V2
