name: CreateProjectOpenAPISpec

authors:
  - Asiya Shaji
  - Humera Sultana

type: SUITE

endpoint: /projects

method: POST

auth: Default

headers:
- 'Content-Type: application/json'

testCases:
    - id: 1
      body: '{
        "name": "proj-{{@Random | 6}}",
        "openAPISpec":"http://13.56.210.25/v2/api-docs"
}'
assertions:
  - "@StatusCode == 200"
  - "@Response.errors == false"
  - "@Response.data.name == @Request.name"

cleanup:
 - DeleteProject

severity: Major

category: Functional

tags:
- V2
