---
parent: "api_v1_projects_projectid_new_autocodeconfig"
name: "ApiV1ProjectsProjectidNewAutocodeconfigPostRoleAdminDisallowedRbac"
description: null
authors:
- "FX Bot"
type: "SUITE"
init: []
path: "/api/v1/projects/{projectId}/new/autocodeconfig"
endpoint: "/api/v1/projects/{{@Random}}/new/autocodeconfig"
method: "POST"
auth: "ROLE_ADMIN"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases:
- id: 1
  body: "{\"createdBy\":\"{{@Random}}\",\"createdDate\":null,\"genPolicy\":\"None\"\
    ,\"generators\":[],\"id\":\"{{@Random}}\",\"inactive\":false,\"modifiedBy\":\"\
    {{@Random}}\",\"modifiedDate\":null,\"openAPISpec\":\"{{@Random}}\",\"project\"\
    :{\"account\":{\"accountType\":\"AZURE\",\"createdBy\":\"{{@Random}}\",\"createdDate\"\
    :null,\"id\":\"{{@Random}}\",\"inactive\":false,\"modifiedBy\":\"{{@Random}}\"\
    ,\"modifiedDate\":null,\"name\":\"{{@Random}}\",\"org\":{\"createdBy\":\"{{@Random}}\"\
    ,\"createdDate\":null,\"id\":\"{{@Random}}\",\"inactive\":false,\"modifiedBy\"\
    :\"{{@Random}}\",\"modifiedDate\":null,\"name\":\"{{@Random}}\",\"version\":\"\
    {{@RandomInteger}}\"},\"region\":\"{{@Random}}\",\"version\":\"{{@RandomInteger}}\"\
    },\"autoGenSuites\":\"{{@RandomInteger}}\",\"branch\":\"{{@Random}}\",\"createdBy\"\
    :\"{{@Random}}\",\"createdDate\":null,\"description\":\"{{@Random}}\",\"genPolicy\"\
    :\"Create\",\"id\":\"{{@Random}}\",\"inactive\":false,\"lastCommit\":\"{{@Random}}\"\
    ,\"lastSync\":null,\"licenses\":[],\"modifiedBy\":\"{{@Random}}\",\"modifiedDate\"\
    :null,\"name\":\"{{@Random}}\",\"openAPISpec\":\"{{@Random}}\",\"org\":{\"createdBy\"\
    :\"{{@Random}}\",\"createdDate\":null,\"id\":\"{{@Random}}\",\"inactive\":false,\"\
    modifiedBy\":\"{{@Random}}\",\"modifiedDate\":null,\"name\":\"{{@Random}}\",\"\
    version\":\"{{@RandomInteger}}\"},\"props\":null,\"url\":\"{{@Random}}\",\"version\"\
    :\"{{@RandomInteger}}\"},\"version\":\"{{@RandomInteger}}\"}"
  inactive: false
assertions:
- "@StatusCode == 401 OR @StatusCode == 403"
cleanup: []
severity: "Major"
category: "RBAC"
tags:
- "V1"
- "OWASP - OTG-IDENT-001 "
- "FX Top 10 - API Vulnerability"
inactive: false
policies: null
autoGenerated: true
